# TextCNN Config

data:
  # number of tokens per example
  n_steps: 10

  # the number of elements from this dataset from which the new dataset will sample.
  shuffle_size: 10000

  # the number elements to process asynchronously in parallel.
  # If not specified, elements will be processed sequentially.
  num_parallel_calls:

  # the number of consecutive elements of this dataset to combine in a single batch.
  batch_size: 128

  # whether the last batch should be dropped in the case it has fewer than batch_size elements;
  train_drop_remainder: True

  # he maximum number of elements that will be buffered when prefetching.
  prefetch_size: 1


model:
  # vocabulary file path
  vocab: tmp/vocab/vocab.txt

  # word embedding size
  emb_size: 300

  # hidden size of RNN unit
  rnn_units: 512

  # number of RNN layers
  rnn_layers: 2

  # Whether to use bidirectional RNN
  rnn_bidi: True

  # Whether to add shortcut between RNN input and RNN output
  rnn_residual: False

  # how to fuse the final state of RNN into a real value vector
  # 'last': select the final state of last layer
  # 'all': concatenate the states of all layers
  rnn_state_scheme: all

  # dropout behind word embedding layer, dropout behind full connected layer
  dropout: 0.5

  # number of categories
  n_classes: 2


train:
  # Random seed for TensorFlow initializers. Setting this value allows consistency between reruns.
  tf_random_seed:

  # Save checkpoints every this many steps.
  save_checkpoints_steps: 10000

  # The maximum number of recent checkpoint files to keep. Defaults to 5.
  # If None or 0, all checkpoint files are kept.
  keep_checkpoint_max: 50

  # Save summaries every this many steps.
  save_summary_steps: 10

  # directory where model parameters, graph, etc are saved.
  model_dir: tmp/result/model/

  # directory where tfrecord of training are saved.
  train_dir: tmp/tfrecord/train

  # directory where tfrecord of evaluation are saved.
  eval_dir: tmp/tfrecord/dev

  # directory where tfrecord of prediction are saved.
  test_dir: tmp/tfrecord/test

  # epochs
  epochs: 20

  # Number of steps for which to train the model.
  # If None, train forever or train until input_fn generates the tf.errors.OutOfRange error or StopIteration exception.
  steps_per_train:

  # Number of steps for which to evaluate model.
  # If None, evaluates until input_fn raises an end-of-input exception.
  steps_per_eval:

  # directory where result of evaluation are saved.
  eval_result_dir: tmp/result/eval/eval.txt

  # directory where result of prediction are saved.
  test_result_dir: tmp/result/test/test.txt